20 3
FRANCISCA Y Y N N N
MARICELA N N Y N N
CARMINA Y N N N N
VICTORIA Y Y N N N
JEAN Y N Y N N
CEZARA N N N Y Y
CONSUELO N Y N N Y
ANTONELA N Y N N N
JASMINA N Y Y N N
EMANUELA Y N N Y N
ADALYN N N Y N N
ANEMONA N Y Y N Y
GLORIA N N Y N N
ANTONIA N N N N Y
МИХАИЛИНА N N Y N N
MAILE Y Y N N N
LYDIA N N Y N Y
DRAGICA Y Y Y Y Y
LAURENTIA N Y Y Y Y
ROBERTINA Y N Y N N
ADALYN ROBERTINA
DRAGICA LAURENTIA JASMINA
ANTONELA LAURENTIA MARICELA JASMINA
